### ISSUE TITLE
tip for clarifying repeat of indention characters

### ISSUE THREAD

**Issue by robertlipe** [nanochess/pretty6502#3]
https://github.com/nanochess/pretty6502/blob/192644256c104e5eee72d7c2e98bfff19629dcab/pretty6502.c#L40

It's not the first printf specifier that we are taught, but %* can do character repeats:

fprintf("%*s", 13, " ");     // will print 13 spaces

**Comment by nanochess** [comment]
That's a good tip. Thanks!
